language: python

services:
  - docker

before_install:
  - docker build -t minikeyvalue -f Dockerfile .

script:
  - docker run -d --name minikeyvalue --hostname localhost minikeyvalue;
  - docker exec minikeyvalue bash -c "go test -v src/lib_test.go src/lib.go";
  - docker exec minikeyvalue bash -c "./tools/test.py && go run tools/thrasher.go && ./tools/rtest.sh";
  - docker container stop minikeyvalue; docker container rm minikeyvalue;
  - docker run -d --name minikeyvalue -e AUTH=/etc/nginx/.htpasswd -e USERPASS=admin:thisisatest --hostname localhost minikeyvalue;
  - docker exec minikeyvalue bash -c "./tools/test.py && ./tools/rtest.sh";
  - docker container stop minikeyvalue; docker container rm minikeyvalue;

